//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;%UserName%&gt;,&lt;/p&gt;
        ///&lt;p&gt;Your password was recently changed. If you did not initiate this password change, you should contact your system administrator immediately.&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;&lt;%SiteURL%&gt;&quot;&gt;&lt;%SiteURL%&gt;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string ChangeUserPwd_Body {
            get {
                return ResourceManager.GetString("ChangeUserPwd_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPlus password change.
        /// </summary>
        public static string ChangeUserPwd_Subject {
            get {
                return ResourceManager.GetString("ChangeUserPwd_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error resetting your password..
        /// </summary>
        public static string Error_CannotResetPassword {
            get {
                return ResourceManager.GetString("Error_CannotResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending the email..
        /// </summary>
        public static string Error_FailedEmail {
            get {
                return ResourceManager.GetString("Error_FailedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please try again..
        /// </summary>
        public static string Error_FailedLogin {
            get {
                return ResourceManager.GetString("Error_FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string Error_PasswordRequired {
            get {
                return ResourceManager.GetString("Error_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown User.
        /// </summary>
        public static string Error_UnknownUser {
            get {
                return ResourceManager.GetString("Error_UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled.
        /// </summary>
        public static string Error_UserDisabled {
            get {
                return ResourceManager.GetString("Error_UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        public static string Error_UserNameRequired {
            get {
                return ResourceManager.GetString("Error_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget your Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email for instructions to reset your password..
        /// </summary>
        public static string ForgotPassword_Confirm {
            get {
                return ResourceManager.GetString("ForgotPassword_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your User Name?.
        /// </summary>
        public static string ForgotPassword_Username {
            get {
                return ResourceManager.GetString("ForgotPassword_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me logged in.
        /// </summary>
        public static string LabelKeepLoggedIn {
            get {
                return ResourceManager.GetString("LabelKeepLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        public static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been logged out..
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently signed in as &lt;b&gt;{0}&lt;/b&gt;..
        /// </summary>
        public static string Manage_Account_SignedInAs {
            get {
                return ResourceManager.GetString("Manage_Account_SignedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Manage_ChangePassword {
            get {
                return ResourceManager.GetString("Manage_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Password.
        /// </summary>
        public static string Manage_CreatePassword {
            get {
                return ResourceManager.GetString("Manage_CreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string Manage_CreatePassword_Message {
            get {
                return ResourceManager.GetString("Manage_CreatePassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfuly changed..
        /// </summary>
        public static string Manage_Message_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Message_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while making changes to your account..
        /// </summary>
        public static string Manage_Message_Error {
            get {
                return ResourceManager.GetString("Manage_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have removed an external login..
        /// </summary>
        public static string Manage_Message_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("Manage_Message_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfuly set a password for your account..
        /// </summary>
        public static string Manage_Message_SetPasswordSuccess {
            get {
                return ResourceManager.GetString("Manage_Message_SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string Manage_SetPassword {
            get {
                return ResourceManager.GetString("Manage_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string Manage_YourAccount {
            get {
                return ResourceManager.GetString("Manage_YourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You may log into the site using the following url and username:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;&lt;%SiteURL%&gt;&quot;&gt;&lt;%SiteURL%&gt;&lt;/a&gt;&lt;br/&gt;
        ///User: &lt;%UserName%&gt;&lt;/p&gt;
        ///&lt;p&gt;Before accessing your account, please use this link to set a password:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;&lt;%SiteURL%&gt;Account/ResetPassword?userid=&lt;%UserId%&gt;&amp;token=&lt;%token%&gt;&quot;&gt;&lt;%SiteURL%&gt;Account/ResetPassword?userid=&lt;%UserId%&gt;&amp;token=&lt;%token%&gt;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string NewUserPwd_Body {
            get {
                return ResourceManager.GetString("NewUserPwd_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New RPlus user notice.
        /// </summary>
        public static string NewUserPwd_Subject {
            get {
                return ResourceManager.GetString("NewUserPwd_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Password_Confirm {
            get {
                return ResourceManager.GetString("Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string Password_Current {
            get {
                return ResourceManager.GetString("Password_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has expired. Before you may access this system, you must reset your password. Please check your email for instructions to reset your password..
        /// </summary>
        public static string Password_Expired {
            get {
                return ResourceManager.GetString("Password_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Password_New {
            get {
                return ResourceManager.GetString("Password_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords should:.
        /// </summary>
        public static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be at least {0} characters.
        /// </summary>
        public static string PasswordPolicy_MinimumLength {
            get {
                return ResourceManager.GetString("PasswordPolicy_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least 1 digit (0-9).
        /// </summary>
        public static string PasswordPolicy_RequireDigit {
            get {
                return ResourceManager.GetString("PasswordPolicy_RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least 1 lower-case letter (a-z).
        /// </summary>
        public static string PasswordPolicy_RequireLowerCase {
            get {
                return ResourceManager.GetString("PasswordPolicy_RequireLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least 1 symbol (not a digit or letter a-z).
        /// </summary>
        public static string PasswordPolicy_RequireNonDigitOrLetter {
            get {
                return ResourceManager.GetString("PasswordPolicy_RequireNonDigitOrLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least 1 upper-case letter (A-Z).
        /// </summary>
        public static string PasswordPolicy_RequireUpperCase {
            get {
                return ResourceManager.GetString("PasswordPolicy_RequireUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me next time..
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request password reset.
        /// </summary>
        public static string RequestPasswordReset {
            get {
                return ResourceManager.GetString("RequestPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed and you have been logged in. You may now use Replenishment+..
        /// </summary>
        public static string ResetPassword_Confirm {
            get {
                return ResourceManager.GetString("ResetPassword_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to try to try again..
        /// </summary>
        public static string ResetPassword_GetToken {
            get {
                return ResourceManager.GetString("ResetPassword_GetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security token is invalid or cannot be used to reset your password..
        /// </summary>
        public static string ResetPassword_InvalidToken {
            get {
                return ResourceManager.GetString("ResetPassword_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        public static string ResetPassword_SetPassword {
            get {
                return ResourceManager.GetString("ResetPassword_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;%UserName%&gt;,&lt;/p&gt;
        ///&lt;p&gt;Your account password has been requested to be reset. If you did not initiate this reset, you should contact your system administrator immediately. Please use the following link to set a new password for your account:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;&lt;%SiteURL%&gt;Account/ResetPassword?userid=&lt;%UserId%&gt;&amp;token=&lt;%token%&gt;&quot;&gt;&lt;%SiteURL%&gt;Account/ResetPassword?userid=&lt;%UserId%&gt;&amp;token=&lt;%token%&gt;&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string ResetUserPwd_Body {
            get {
                return ResourceManager.GetString("ResetUserPwd_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPlus password reset.
        /// </summary>
        public static string ResetUserPwd_Subject {
            get {
                return ResourceManager.GetString("ResetUserPwd_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to continue.
        /// </summary>
        public static string SignInToContinue {
            get {
                return ResourceManager.GetString("SignInToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
