//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Admin_UserManagement_AddButton {
            get {
                return ResourceManager.GetString("Admin_UserManagement_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string Admin_UserManagement_AddUserLabel {
            get {
                return ResourceManager.GetString("Admin_UserManagement_AddUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Admin_UserManagement_CancelButton {
            get {
                return ResourceManager.GetString("Admin_UserManagement_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Admin_UserManagement_EmailLabel {
            get {
                return ResourceManager.GetString("Admin_UserManagement_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Admin_UserManagement_UserNameLabel {
            get {
                return ResourceManager.GetString("Admin_UserManagement_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Lead Time Compression.
        /// </summary>
        public static string Settings_AllowLeadTimeCompression {
            get {
                return ResourceManager.GetString("Settings_AllowLeadTimeCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline Formatting Region.
        /// </summary>
        public static string Settings_BaselineFormattingRegion {
            get {
                return ResourceManager.GetString("Settings_BaselineFormattingRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Settings_Close_Btn {
            get {
                return ResourceManager.GetString("Settings_Close_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string Settings_DateFormat {
            get {
                return ResourceManager.GetString("Settings_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Inventory Alert Level.
        /// </summary>
        public static string Settings_DefaultInventoryAlertLevel {
            get {
                return ResourceManager.GetString("Settings_DefaultInventoryAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Order Spike Alert Level.
        /// </summary>
        public static string Settings_DefaultOrderSpikeAlertLevel {
            get {
                return ResourceManager.GetString("Settings_DefaultOrderSpikeAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Order Spike Horizon Level.
        /// </summary>
        public static string Settings_DefaultOrderSpikeHorizonLevel {
            get {
                return ResourceManager.GetString("Settings_DefaultOrderSpikeHorizonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore NB Demand Outside Processing Window.
        /// </summary>
        public static string Settings_DeleteImportedNBDemandOutsideProcessingWindow {
            get {
                return ResourceManager.GetString("Settings_DeleteImportedNBDemandOutsideProcessingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        public static string Settings_Delimiter {
            get {
                return ResourceManager.GetString("Settings_Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Order Window (days).
        /// </summary>
        public static string Settings_DemandOrderWindow {
            get {
                return ResourceManager.GetString("Settings_DemandOrderWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Numeric Format.
        /// </summary>
        public static string Settings_ExpectedNumericFormat {
            get {
                return ResourceManager.GetString("Settings_ExpectedNumericFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External API Access.
        /// </summary>
        public static string Settings_ExternalApiAccess {
            get {
                return ResourceManager.GetString("Settings_ExternalApiAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks Of Forecasted Demand.
        /// </summary>
        public static string Settings_ForecastedDemandLookAhead {
            get {
                return ResourceManager.GetString("Settings_ForecastedDemandLookAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffers and Order Processing.
        /// </summary>
        public static string Settings_Global_BuffersAndOrderProcessing {
            get {
                return ResourceManager.GetString("Settings_Global_BuffersAndOrderProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Settings.
        /// </summary>
        public static string Settings_Global_DateTimeSettings {
            get {
                return ResourceManager.GetString("Settings_Global_DateTimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string Settings_Global_DisplayName {
            get {
                return ResourceManager.GetString("Settings_Global_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Settings_Global_Field {
            get {
                return ResourceManager.GetString("Settings_Global_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasted Demand and Forecasted Daily Usage (FDU).
        /// </summary>
        public static string Settings_Global_ForecastedDemand {
            get {
                return ResourceManager.GetString("Settings_Global_ForecastedDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Data Exchange (Import &amp; Export).
        /// </summary>
        public static string Settings_Global_ImportExportDataExchange {
            get {
                return ResourceManager.GetString("Settings_Global_ImportExportDataExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations and Alerts.
        /// </summary>
        public static string Settings_Global_RecommendationsAndAlerts {
            get {
                return ResourceManager.GetString("Settings_Global_RecommendationsAndAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Fields.
        /// </summary>
        public static string Settings_Global_UDF {
            get {
                return ResourceManager.GetString("Settings_Global_UDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Settings_Grids_Column_Label {
            get {
                return ResourceManager.GetString("Settings_Grids_Column_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Precision.
        /// </summary>
        public static string Settings_Grids_DecimalPrecision_Label {
            get {
                return ResourceManager.GetString("Settings_Grids_DecimalPrecision_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        public static string Settings_Grids_DefaultPrecisionFormat {
            get {
                return ResourceManager.GetString("Settings_Grids_DefaultPrecisionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Settings_Grids_NoPrecisionLabel {
            get {
                return ResourceManager.GetString("Settings_Grids_NoPrecisionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Capture.
        /// </summary>
        public static string Settings_HistoryCapture {
            get {
                return ResourceManager.GetString("Settings_HistoryCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Of History To Maintain.
        /// </summary>
        public static string Settings_HistoryCaptureDaysToKeep {
            get {
                return ResourceManager.GetString("Settings_HistoryCaptureDaysToKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Spikes in Available Stock.
        /// </summary>
        public static string Settings_IncludeSpikesAsDemandAllocation {
            get {
                return ResourceManager.GetString("Settings_IncludeSpikesAsDemandAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time Zone.
        /// </summary>
        public static string Settings_LocalTimeZone {
            get {
                return ResourceManager.GetString("Settings_LocalTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP calculations are disabled.
        /// </summary>
        public static string Settings_Mrp_Disabled {
            get {
                return ResourceManager.GetString("Settings_Mrp_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform MRP Netting after import? (Full MRP).
        /// </summary>
        public static string Settings_Mrp_DoMaterialRequirementsNettingAfterImport {
            get {
                return ResourceManager.GetString("Settings_Mrp_DoMaterialRequirementsNettingAfterImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform MRP Netting when creating new orders? (Net-Change MRP).
        /// </summary>
        public static string Settings_Mrp_DoMaterialRequirementsNettingWhenCreatingOrders {
            get {
                return ResourceManager.GetString("Settings_Mrp_DoMaterialRequirementsNettingWhenCreatingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically create supply orders for Min/Max parts?.
        /// </summary>
        public static string Settings_Mrp_EnableAutoCreateMinMaxSupplyOrders {
            get {
                return ResourceManager.GetString("Settings_Mrp_EnableAutoCreateMinMaxSupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically create supply orders for Non-Buffered parts?.
        /// </summary>
        public static string Settings_Mrp_EnableAutoCreateNonBufferedSupplyOrders {
            get {
                return ResourceManager.GetString("Settings_Mrp_EnableAutoCreateNonBufferedSupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Material Requirements Planning.
        /// </summary>
        public static string Settings_Mrp_EnableMaterialRequirementsPlanning {
            get {
                return ResourceManager.GetString("Settings_Mrp_EnableMaterialRequirementsPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These options will allow R+ to automatically create Supply Orders during MRP Netting to meet open demand and will only affect parts in a Bill of Materials..
        /// </summary>
        public static string Settings_Mrp_mrpFeatures1 {
            get {
                return ResourceManager.GetString("Settings_Mrp_mrpFeatures1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During MRP Netting, these settings will limit how far forward R+ will try to create orders. These values are added to the part&apos;s R+ Lead Time. e.g. If set to &apos;5&apos;, and a part has an R+ Lead Time of 5 days, R+ will not create an order until the current date is within 10 working days of the demand due date..
        /// </summary>
        public static string Settings_Mrp_mrpFeatures2 {
            get {
                return ResourceManager.GetString("Settings_Mrp_mrpFeatures2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ will automatically do MRP Netting for ALL imported demand orders (Sales Orders and Work Orders). Imported demand records should not contain any child demand..
        /// </summary>
        public static string Settings_Mrp_mrpNettingFull {
            get {
                return ResourceManager.GetString("Settings_Mrp_mrpNettingFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ will only perform MRP Netting when creating orders manually or approving recommended orders. R+ will assume that all imported demand orders have already been netted by your MRP system prior to import..
        /// </summary>
        public static string Settings_Mrp_mrpNettingNetChange {
            get {
                return ResourceManager.GetString("Settings_Mrp_mrpNettingNetChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If &apos;MRP Netting after import&apos; is selected, we suggest also enabling &apos;MRP Netting when creating new orders&apos;. This will ensure consistent behavior..
        /// </summary>
        public static string Settings_Mrp_mrpNettingSuggestion1 {
            get {
                return ResourceManager.GetString("Settings_Mrp_mrpNettingSuggestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Processing Window for Sales Orders.
        /// </summary>
        public static string Settings_Mrp_SalesOrderDemandProcessingWindow {
            get {
                return ResourceManager.GetString("Settings_Mrp_SalesOrderDemandProcessingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Processing Window for Work Orders.
        /// </summary>
        public static string Settings_Mrp_WorkOrderDemandProcessingWindow {
            get {
                return ResourceManager.GetString("Settings_Mrp_WorkOrderDemandProcessingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Tokens.
        /// </summary>
        public static string Settings_Nav_ApiTokens {
            get {
                return ResourceManager.GetString("Settings_Nav_ApiTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time Format.
        /// </summary>
        public static string Settings_Nav_DateTime {
            get {
                return ResourceManager.GetString("Settings_Nav_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Part Filter.
        /// </summary>
        public static string Settings_Nav_GlobalFilter {
            get {
                return ResourceManager.GetString("Settings_Nav_GlobalFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string Settings_Nav_GlobalSettings {
            get {
                return ResourceManager.GetString("Settings_Nav_GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grids.
        /// </summary>
        public static string Settings_Nav_Grids {
            get {
                return ResourceManager.GetString("Settings_Nav_Grids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Requirements Planning.
        /// </summary>
        public static string Settings_Nav_MaterialRequirements {
            get {
                return ResourceManager.GetString("Settings_Nav_MaterialRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitewide.
        /// </summary>
        public static string Settings_Nav_Sitewide {
            get {
                return ResourceManager.GetString("Settings_Nav_Sitewide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string Settings_Nav_UserAccount {
            get {
                return ResourceManager.GetString("Settings_Nav_UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Settings_Nav_UserManagement {
            get {
                return ResourceManager.GetString("Settings_Nav_UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Complexity Requirements.
        /// </summary>
        public static string Settings_PasswordComplexity {
            get {
                return ResourceManager.GetString("Settings_PasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a format.
        /// </summary>
        public static string Settings_PleaseSelectAFormat {
            get {
                return ResourceManager.GetString("Settings_PleaseSelectAFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock-Out Lead Time Horizon.
        /// </summary>
        public static string Settings_ProjectedStockOutLeadTimeHorizon {
            get {
                return ResourceManager.GetString("Settings_ProjectedStockOutLeadTimeHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string Settings_PurchaseOrder {
            get {
                return ResourceManager.GetString("Settings_PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_Reset_Btn {
            get {
                return ResourceManager.GetString("Settings_Reset_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Buffer Values to One.
        /// </summary>
        public static string Settings_RoundBufferValuesToOne {
            get {
                return ResourceManager.GetString("Settings_RoundBufferValuesToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        public static string Settings_SalesOrder {
            get {
                return ResourceManager.GetString("Settings_SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Settings_SaveChanges_Btn {
            get {
                return ResourceManager.GetString("Settings_SaveChanges_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string Settings_SaveChangesConfirmation {
            get {
                return ResourceManager.GetString("Settings_SaveChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t save, your changes will be lost..
        /// </summary>
        public static string Settings_SaveChangesDetail {
            get {
                return ResourceManager.GetString("Settings_SaveChangesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string Settings_UnsavedChanges {
            get {
                return ResourceManager.GetString("Settings_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        public static string Settings_User_DateFormat {
            get {
                return ResourceManager.GetString("Settings_User_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date columns found.
        /// </summary>
        public static string Settings_User_DateFormat_NoneFound {
            get {
                return ResourceManager.GetString("Settings_User_DateFormat_NoneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date/Time Format.
        /// </summary>
        public static string Settings_User_DateFormat_Title {
            get {
                return ResourceManager.GetString("Settings_User_DateFormat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Precision.
        /// </summary>
        public static string Settings_User_DecimalPrecision {
            get {
                return ResourceManager.GetString("Settings_User_DecimalPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Precision.
        /// </summary>
        public static string Settings_User_DecimalPrecision_Title {
            get {
                return ResourceManager.GetString("Settings_User_DecimalPrecision_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Length?.
        /// </summary>
        public static string Settings_User_MinimumLength {
            get {
                return ResourceManager.GetString("Settings_User_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Settings_User_Password {
            get {
                return ResourceManager.GetString("Settings_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Complexity.
        /// </summary>
        public static string Settings_User_PasswordComplexity {
            get {
                return ResourceManager.GetString("Settings_User_PasswordComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Max Age (in days).
        /// </summary>
        public static string Settings_User_PasswordMaxAgeDays {
            get {
                return ResourceManager.GetString("Settings_User_PasswordMaxAgeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require at least 1 digit? (0-9).
        /// </summary>
        public static string Settings_User_RequireDigit {
            get {
                return ResourceManager.GetString("Settings_User_RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require at least 1 lowercase? (a-z).
        /// </summary>
        public static string Settings_User_RequireLowerCase {
            get {
                return ResourceManager.GetString("Settings_User_RequireLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require a non-letter or digit?.
        /// </summary>
        public static string Settings_User_RequireNonDigitLetter {
            get {
                return ResourceManager.GetString("Settings_User_RequireNonDigitLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any character not in the ranges of 0-9, a-z, or A-Z. Examples: !, %, *, $.
        /// </summary>
        public static string Settings_User_RequireNonDigitLetter_Title {
            get {
                return ResourceManager.GetString("Settings_User_RequireNonDigitLetter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require at least 1 uppercase? (A-Z).
        /// </summary>
        public static string Settings_User_RequireUpperCase {
            get {
                return ResourceManager.GetString("Settings_User_RequireUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Grid.
        /// </summary>
        public static string Settings_User_UnknownGrid {
            get {
                return ResourceManager.GetString("Settings_User_UnknownGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined1.
        /// </summary>
        public static string Settings_UserDefined1 {
            get {
                return ResourceManager.GetString("Settings_UserDefined1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined2.
        /// </summary>
        public static string Settings_UserDefined2 {
            get {
                return ResourceManager.GetString("Settings_UserDefined2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined3.
        /// </summary>
        public static string Settings_UserDefined3 {
            get {
                return ResourceManager.GetString("Settings_UserDefined3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined4.
        /// </summary>
        public static string Settings_UserDefined4 {
            get {
                return ResourceManager.GetString("Settings_UserDefined4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined5.
        /// </summary>
        public static string Settings_UserDefined5 {
            get {
                return ResourceManager.GetString("Settings_UserDefined5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined6.
        /// </summary>
        public static string Settings_UserDefined6 {
            get {
                return ResourceManager.GetString("Settings_UserDefined6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined7.
        /// </summary>
        public static string Settings_UserDefined7 {
            get {
                return ResourceManager.GetString("Settings_UserDefined7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefined8.
        /// </summary>
        public static string Settings_UserDefined8 {
            get {
                return ResourceManager.GetString("Settings_UserDefined8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order.
        /// </summary>
        public static string Settings_WorkOrder {
            get {
                return ResourceManager.GetString("Settings_WorkOrder", resourceCulture);
            }
        }
    }
}
