//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alerts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Alerts", typeof(Alerts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note.
        /// </summary>
        public static string AddANote {
            get {
                return ResourceManager.GetString("AddANote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A Reminder.
        /// </summary>
        public static string AddAReminder {
            get {
                return ResourceManager.GetString("AddAReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Factor.
        /// </summary>
        public static string AdjustmentFactor {
            get {
                return ResourceManager.GetString("AdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in Legacy Alerts.
        /// </summary>
        public static string Alerts_Menu_ViewInLegacyAlerts {
            get {
                return ResourceManager.GetString("Alerts_Menu_ViewInLegacyAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string AlertsStr {
            get {
                return ResourceManager.GetString("AlertsStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Activity.
        /// </summary>
        public static string AllActivity {
            get {
                return ResourceManager.GetString("AllActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Stock.
        /// </summary>
        public static string AvailableStock {
            get {
                return ResourceManager.GetString("AvailableStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Daily Usage:.
        /// </summary>
        public static string AvgDailyUsage {
            get {
                return ResourceManager.GetString("AvgDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to view reminders.
        /// </summary>
        public static string ClickToViewReminders {
            get {
                return ResourceManager.GetString("ClickToViewReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committed.
        /// </summary>
        public static string Committed {
            get {
                return ResourceManager.GetString("Committed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory.
        /// </summary>
        public static string CurrentInventory {
            get {
                return ResourceManager.GetString("CurrentInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory - All.
        /// </summary>
        public static string CurrentInventoryAll {
            get {
                return ResourceManager.GetString("CurrentInventoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory - Critical.
        /// </summary>
        public static string CurrentInventoryCritical {
            get {
                return ResourceManager.GetString("CurrentInventoryCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory - High.
        /// </summary>
        public static string CurrentInventoryHigh {
            get {
                return ResourceManager.GetString("CurrentInventoryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory - Medium.
        /// </summary>
        public static string CurrentInventoryMedium {
            get {
                return ResourceManager.GetString("CurrentInventoryMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s) early.
        /// </summary>
        public static string DaysEarly {
            get {
                return ResourceManager.GetString("DaysEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s) late.
        /// </summary>
        public static string DaysLate {
            get {
                return ResourceManager.GetString("DaysLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        public static string Demand {
            get {
                return ResourceManager.GetString("Demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Allocations.
        /// </summary>
        public static string DemandAllocations {
            get {
                return ResourceManager.GetString("DemandAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported.
        /// </summary>
        public static string Exported {
            get {
                return ResourceManager.GetString("Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Inventory.
        /// </summary>
        public static string IssuedInventory {
            get {
                return ResourceManager.GetString("IssuedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Late {
            get {
                return ResourceManager.GetString("Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc.
        /// </summary>
        public static string Loc {
            get {
                return ResourceManager.GetString("Loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Summary.
        /// </summary>
        public static string LTMSummary {
            get {
                return ResourceManager.GetString("LTMSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Summary - All.
        /// </summary>
        public static string LTMSummaryAll {
            get {
                return ResourceManager.GetString("LTMSummaryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Summary - High.
        /// </summary>
        public static string LTMSummaryHigh {
            get {
                return ResourceManager.GetString("LTMSummaryHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Summary - Low.
        /// </summary>
        public static string LTMSummaryLow {
            get {
                return ResourceManager.GetString("LTMSummaryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Summary - Medium.
        /// </summary>
        public static string LTMSummaryMedium {
            get {
                return ResourceManager.GetString("LTMSummaryMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Synchronization Alert.
        /// </summary>
        public static string MaterialSynchronizationAlert {
            get {
                return ResourceManager.GetString("MaterialSynchronizationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSA - All.
        /// </summary>
        public static string MSAAll {
            get {
                return ResourceManager.GetString("MSAAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSA - Critical.
        /// </summary>
        public static string MSACritical {
            get {
                return ResourceManager.GetString("MSACritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSA - High.
        /// </summary>
        public static string MSAHigh {
            get {
                return ResourceManager.GetString("MSAHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an alert.
        /// </summary>
        public static string NoAlertSelected {
            get {
                return ResourceManager.GetString("NoAlertSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Execution Alerts.
        /// </summary>
        public static string NoExecutionAlerts {
            get {
                return ResourceManager.GetString("NoExecutionAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet.
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hand Inventory.
        /// </summary>
        public static string OnHandInventory {
            get {
                return ResourceManager.GetString("OnHandInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PO.
        /// </summary>
        public static string OpenPO {
            get {
                return ResourceManager.GetString("OpenPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Supply.
        /// </summary>
        public static string OpenSupply {
            get {
                return ResourceManager.GetString("OpenSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open WO.
        /// </summary>
        public static string OpenWO {
            get {
                return ResourceManager.GetString("OpenWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order(s).
        /// </summary>
        public static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Spike Priority.
        /// </summary>
        public static string OrderSpikePriority {
            get {
                return ResourceManager.GetString("OrderSpikePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part ID.
        /// </summary>
        public static string PartID {
            get {
                return ResourceManager.GetString("PartID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Type.
        /// </summary>
        public static string PartType {
            get {
                return ResourceManager.GetString("PartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner Code.
        /// </summary>
        public static string PlannerCode {
            get {
                return ResourceManager.GetString("PlannerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out.
        /// </summary>
        public static string ProjectedStockOut {
            get {
                return ResourceManager.GetString("ProjectedStockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out - All.
        /// </summary>
        public static string ProjectedStockOutAll {
            get {
                return ResourceManager.GetString("ProjectedStockOutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out - Critical.
        /// </summary>
        public static string ProjectedStockOutCritical {
            get {
                return ResourceManager.GetString("ProjectedStockOutCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out - High.
        /// </summary>
        public static string ProjectedStockOutHigh {
            get {
                return ResourceManager.GetString("ProjectedStockOutHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out - Medium.
        /// </summary>
        public static string ProjectedStockOutMedium {
            get {
                return ResourceManager.GetString("ProjectedStockOutMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promise Date.
        /// </summary>
        public static string PromiseDate {
            get {
                return ResourceManager.GetString("PromiseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Point.
        /// </summary>
        public static string ReorderPoint {
            get {
                return ResourceManager.GetString("ReorderPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev.
        /// </summary>
        public static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ Alert.
        /// </summary>
        public static string RPlusAlert {
            get {
                return ResourceManager.GetString("RPlusAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to.
        /// </summary>
        public static string rule_AppliesTo {
            get {
                return ResourceManager.GetString("rule_AppliesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has current or past due demand, but no current inventory.
        /// </summary>
        public static string rule_CurrentInventory_Critical1 {
            get {
                return ResourceManager.GetString("rule_CurrentInventory_Critical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand exceeds current inventory.
        /// </summary>
        public static string rule_CurrentInventory_High1 {
            get {
                return ResourceManager.GetString("rule_CurrentInventory_High1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current inventory, and there is no demand.
        /// </summary>
        public static string rule_CurrentInventory_High2 {
            get {
                return ResourceManager.GetString("rule_CurrentInventory_High2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order due to arrive in less than 3% of the Lead Time.
        /// </summary>
        public static string rule_LTM_High1 {
            get {
                return ResourceManager.GetString("rule_LTM_High1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order due to arrive in Less that 11% of Lead Time but more than 7% of Lead Time.
        /// </summary>
        public static string rule_LTM_Low1 {
            get {
                return ResourceManager.GetString("rule_LTM_Low1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order due to arrive in less that 7% of Lead Time but more that 3% of Lead Time.
        /// </summary>
        public static string rule_LTM_Medium1 {
            get {
                return ResourceManager.GetString("rule_LTM_Medium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has open supply and demand within lead time.
        /// </summary>
        public static string rule_MaterialSynchronizationAlert_B_Critical1 {
            get {
                return ResourceManager.GetString("rule_MaterialSynchronizationAlert_B_Critical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QOH (current on hand inventory) &amp;gt;=0 and if Running Balance is &amp;lt;= 0 at any time during the Lead Time Horizon.
        /// </summary>
        public static string rule_MaterialSynchronizationAlert_B_Critical2 {
            get {
                return ResourceManager.GetString("rule_MaterialSynchronizationAlert_B_Critical2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has open supply/demand within lead time.
        /// </summary>
        public static string rule_MaterialSynchronizationAlert_High1 {
            get {
                return ResourceManager.GetString("rule_MaterialSynchronizationAlert_High1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QOH (current on hand inventory) &amp;gt;=0 and Running Balance is &amp;gt;0 and &amp;lt;= % ToR at any time during the Lead Time Horizon.
        /// </summary>
        public static string rule_MaterialSynchronizationAlert_High2 {
            get {
                return ResourceManager.GetString("rule_MaterialSynchronizationAlert_High2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has negative running balance in the past.
        /// </summary>
        public static string rule_MaterialSynchronizationAlert_NB_Critical1 {
            get {
                return ResourceManager.GetString("rule_MaterialSynchronizationAlert_NB_Critical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has negative running balance at any time during the Lead Time Horizon.
        /// </summary>
        public static string rule_MaterialSynchronizationAlert_NB_Critical2 {
            get {
                return ResourceManager.GetString("rule_MaterialSynchronizationAlert_NB_Critical2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not included in.
        /// </summary>
        public static string rule_NotIncludedIn {
            get {
                return ResourceManager.GetString("rule_NotIncludedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory Level is less than % of red zone as defined by inventory alert level in buffer profile (or system default for alert level).
        /// </summary>
        public static string rule_ProjectedStockOut_High1 {
            get {
                return ResourceManager.GetString("rule_ProjectedStockOut_High1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory Level is less than or equal to Top of Red (ToR).
        /// </summary>
        public static string rule_ProjectedStockOut_Medium1 {
            get {
                return ResourceManager.GetString("rule_ProjectedStockOut_Medium1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Balance.
        /// </summary>
        public static string RunningBalance {
            get {
                return ResourceManager.GetString("RunningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO Demand.
        /// </summary>
        public static string SODemand {
            get {
                return ResourceManager.GetString("SODemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -SPIKE.
        /// </summary>
        public static string SPIKE {
            get {
                return ResourceManager.GetString("SPIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Status3 {
            get {
                return ResourceManager.GetString("Status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Status4 {
            get {
                return ResourceManager.GetString("Status4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK OUT.
        /// </summary>
        public static string StockOut {
            get {
                return ResourceManager.GetString("StockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCK OUT WITH DEMAND.
        /// </summary>
        public static string StockOutWithDemand {
            get {
                return ResourceManager.GetString("StockOutWithDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Order Note.
        /// </summary>
        public static string SupplyOrderNote {
            get {
                return ResourceManager.GetString("SupplyOrderNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Orders.
        /// </summary>
        public static string SupplyOrders {
            get {
                return ResourceManager.GetString("SupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Of Green.
        /// </summary>
        public static string TopOfGreen {
            get {
                return ResourceManager.GetString("TopOfGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Of Red.
        /// </summary>
        public static string TopOfRed {
            get {
                return ResourceManager.GetString("TopOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Of Yellow.
        /// </summary>
        public static string TopOfYellow {
            get {
                return ResourceManager.GetString("TopOfYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        public static string VendorID {
            get {
                return ResourceManager.GetString("VendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO Demand.
        /// </summary>
        public static string WODemand {
            get {
                return ResourceManager.GetString("WODemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
