//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BufferProfileEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BufferProfileEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.BufferProfileEditor", typeof(BufferProfileEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to average number of days between order cycles.
        /// </summary>
        public static string AverageNumberOfDaysBetweenOrderCycles {
            get {
                return ResourceManager.GetString("AverageNumberOfDaysBetweenOrderCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Profile.
        /// </summary>
        public static string BufferProfile {
            get {
                return ResourceManager.GetString("BufferProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Profiles.
        /// </summary>
        public static string BufferProfiles {
            get {
                return ResourceManager.GetString("BufferProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Zone Base.
        /// </summary>
        public static string GreenZoneBase {
            get {
                return ResourceManager.GetString("GreenZoneBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Zone Calculation Method.
        /// </summary>
        public static string GreenZoneCalculationMethod {
            get {
                return ResourceManager.GetString("GreenZoneCalculationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Alert Level.
        /// </summary>
        public static string InventoryAlertLevel {
            get {
                return ResourceManager.GetString("InventoryAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time.
        /// </summary>
        public static string LeadTime {
            get {
                return ResourceManager.GetString("LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cycle Days.
        /// </summary>
        public static string OrderCycleDays {
            get {
                return ResourceManager.GetString("OrderCycleDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Spike Horizon.
        /// </summary>
        public static string OrderSpikeHorizon {
            get {
                return ResourceManager.GetString("OrderSpikeHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Spike Threshold Level.
        /// </summary>
        public static string OrderSpikeThresholdLevel {
            get {
                return ResourceManager.GetString("OrderSpikeThresholdLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Top of Red.
        /// </summary>
        public static string PercentOfTopOfRed {
            get {
                return ResourceManager.GetString("PercentOfTopOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of usage over lead time.
        /// </summary>
        public static string PercentOfUsageOverLeadTime {
            get {
                return ResourceManager.GetString("PercentOfUsageOverLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Red Zone Base.
        /// </summary>
        public static string PercentRedZoneBase {
            get {
                return ResourceManager.GetString("PercentRedZoneBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Definition.
        /// </summary>
        public static string ProfileDefinition {
            get {
                return ResourceManager.GetString("ProfileDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile saved successfully.
        /// </summary>
        public static string ProfileSavedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Zone Base.
        /// </summary>
        public static string RedZoneBase {
            get {
                return ResourceManager.GetString("RedZoneBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Zone.
        /// </summary>
        public static string SafetyZone {
            get {
                return ResourceManager.GetString("SafetyZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilter {
            get {
                return ResourceManager.GetString("SelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The R+ Alert is equal to Top of Yellow.
        /// </summary>
        public static string TheRPlusAlertIsEqualToTopOfYellow {
            get {
                return ResourceManager.GetString("TheRPlusAlertIsEqualToTopOfYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Details are not supported for this part type.
        /// </summary>
        public static string UnsupportedPart {
            get {
                return ResourceManager.GetString("UnsupportedPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Order Cycle for green zone.
        /// </summary>
        public static string UseOrderCycleForGreenZone {
            get {
                return ResourceManager.GetString("UseOrderCycleForGreenZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use part Minimum Order Quantity for green zone.
        /// </summary>
        public static string UsePartMinimumOrderQuantityForGreenZone {
            get {
                return ResourceManager.GetString("UsePartMinimumOrderQuantityForGreenZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use % of usage over lead time.
        /// </summary>
        public static string UsePercentOfUsageOverLeadTime {
            get {
                return ResourceManager.GetString("UsePercentOfUsageOverLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System Spike Horizon of.
        /// </summary>
        public static string UseSystemSpikeHorizonOf {
            get {
                return ResourceManager.GetString("UseSystemSpikeHorizonOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Zone Base.
        /// </summary>
        public static string YellowZoneBase {
            get {
                return ResourceManager.GetString("YellowZoneBase", resourceCulture);
            }
        }
    }
}
