//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Export {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Export() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Export", typeof(Export).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of Material.
        /// </summary>
        public static string BillOfMaterial {
            get {
                return ResourceManager.GetString("BillOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Profile.
        /// </summary>
        public static string BufferProfile {
            get {
                return ResourceManager.GetString("BufferProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Order.
        /// </summary>
        public static string DemandOrder {
            get {
                return ResourceManager.GetString("DemandOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportStr {
            get {
                return ResourceManager.GetString("ExportStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasted Demand.
        /// </summary>
        public static string ForecastedDemand {
            get {
                return ResourceManager.GetString("ForecastedDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers Only.
        /// </summary>
        public static string HeadersOnly {
            get {
                return ResourceManager.GetString("HeadersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Augment.
        /// </summary>
        public static string PartAugment {
            get {
                return ResourceManager.GetString("PartAugment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Buffer Sizing.
        /// </summary>
        public static string PartBufferSizing {
            get {
                return ResourceManager.GetString("PartBufferSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Inventory.
        /// </summary>
        public static string PartInventory {
            get {
                return ResourceManager.GetString("PartInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Adjustment Factor.
        /// </summary>
        public static string PlannedAdjustmentFactor {
            get {
                return ResourceManager.GetString("PlannedAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select tables for export.
        /// </summary>
        public static string PleaseSelectTables {
            get {
                return ResourceManager.GetString("PleaseSelectTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which data tables to export:.
        /// </summary>
        public static string SelectTablesToExport {
            get {
                return ResourceManager.GetString("SelectTablesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Order.
        /// </summary>
        public static string SupplyOrder {
            get {
                return ResourceManager.GetString("SupplyOrder", resourceCulture);
            }
        }
    }
}
