//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected.
        /// </summary>
        public static string AllSelected {
            get {
                return ResourceManager.GetString("AllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A background process is running..
        /// </summary>
        public static string BackgroundProcessing {
            get {
                return ResourceManager.GetString("BackgroundProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is disabled until execution completes..
        /// </summary>
        public static string BackgroundProcessing_FeatureDisabled {
            get {
                return ResourceManager.GetString("BackgroundProcessing_FeatureDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Time Zone.
        /// </summary>
        public static string ConfiguredTimeZone {
            get {
                return ResourceManager.GetString("ConfiguredTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string DisplayLang_de {
            get {
                return ResourceManager.GetString("DisplayLang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string DisplayLang_en {
            get {
                return ResourceManager.GetString("DisplayLang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (UK).
        /// </summary>
        public static string DisplayLang_en_gb {
            get {
                return ResourceManager.GetString("DisplayLang_en_gb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string DisplayLang_es {
            get {
                return ResourceManager.GetString("DisplayLang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish (Latin America).
        /// </summary>
        public static string DisplayLang_es_419 {
            get {
                return ResourceManager.GetString("DisplayLang_es_419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string DisplayLang_fi {
            get {
                return ResourceManager.GetString("DisplayLang_fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string DisplayLang_fr {
            get {
                return ResourceManager.GetString("DisplayLang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string DisplayLang_hu {
            get {
                return ResourceManager.GetString("DisplayLang_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string DisplayLang_ko {
            get {
                return ResourceManager.GetString("DisplayLang_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Portugal).
        /// </summary>
        public static string DisplayLang_pt_pt {
            get {
                return ResourceManager.GetString("DisplayLang_pt_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string DisplayLang_ru {
            get {
                return ResourceManager.GetString("DisplayLang_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string DisplayLang_tr {
            get {
                return ResourceManager.GetString("DisplayLang_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Disabled.
        /// </summary>
        public static string FilterDisabled {
            get {
                return ResourceManager.GetString("FilterDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Home_About_ApplicationLabel {
            get {
                return ResourceManager.GetString("Home_About_ApplicationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Home_About_VersionLabel {
            get {
                return ResourceManager.GetString("Home_About_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Index_PageTitle {
            get {
                return ResourceManager.GetString("Home_Index_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Languages.
        /// </summary>
        public static string LanguageDropDown_AvailableLanguages {
            get {
                return ResourceManager.GetString("LanguageDropDown_AvailableLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Language.
        /// </summary>
        public static string LanguageDropDown_CurrentLanguage {
            get {
                return ResourceManager.GetString("LanguageDropDown_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_About_Title {
            get {
                return ResourceManager.GetString("Nav_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        public static string Nav_Account_Manage_Title {
            get {
                return ResourceManager.GetString("Nav_Account_Manage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string Nav_Admin_GlobalSettings_Title {
            get {
                return ResourceManager.GetString("Nav_Admin_GlobalSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Requirements.
        /// </summary>
        public static string Nav_Admin_MaterialRequirements_Title {
            get {
                return ResourceManager.GetString("Nav_Admin_MaterialRequirements_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Admin_Settings_Title {
            get {
                return ResourceManager.GetString("Nav_Admin_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Nav_Admin_Title {
            get {
                return ResourceManager.GetString("Nav_Admin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string Nav_Admin_UserMgmt_Title {
            get {
                return ResourceManager.GetString("Nav_Admin_UserMgmt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Supply Order Notes.
        /// </summary>
        public static string Nav_Alerts_CurrentSupplyOrderNotes {
            get {
                return ResourceManager.GetString("Nav_Alerts_CurrentSupplyOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Supply Order Notes.
        /// </summary>
        public static string Nav_Alerts_NoSupplyOrderNotes {
            get {
                return ResourceManager.GetString("Nav_Alerts_NoSupplyOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outstanding Supply Order Notes.
        /// </summary>
        public static string Nav_Alerts_OutstandingSupplyOrderNotes {
            get {
                return ResourceManager.GetString("Nav_Alerts_OutstandingSupplyOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue Supply Order Notes.
        /// </summary>
        public static string Nav_Alerts_OverdueSupplyOrderNotes {
            get {
                return ResourceManager.GetString("Nav_Alerts_OverdueSupplyOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Nav_Alerts_Title {
            get {
                return ResourceManager.GetString("Nav_Alerts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Inventory.
        /// </summary>
        public static string Nav_AlertsCurrentInventory_Title {
            get {
                return ResourceManager.GetString("Nav_AlertsCurrentInventory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM.
        /// </summary>
        public static string Nav_AlertsLTMSummary_Title {
            get {
                return ResourceManager.GetString("Nav_AlertsLTMSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSA.
        /// </summary>
        public static string Nav_AlertsMSASummary_Title {
            get {
                return ResourceManager.GetString("Nav_AlertsMSASummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out.
        /// </summary>
        public static string Nav_AlertsProjectedStockOut_Title {
            get {
                return ResourceManager.GetString("Nav_AlertsProjectedStockOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Explorer.
        /// </summary>
        public static string Nav_ApiExplorer {
            get {
                return ResourceManager.GetString("Nav_ApiExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill of Materials.
        /// </summary>
        public static string Nav_BoM_Title {
            get {
                return ResourceManager.GetString("Nav_BoM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string Nav_DataMgmt_Export_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string Nav_DataMgmt_FullTitle {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_FullTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Import.
        /// </summary>
        public static string Nav_DataMgmt_Import_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_All_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_All_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_Completed_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_Completed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_Failed_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Upload.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_NewUpload_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_NewUpload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_Processing_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_Processing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_Succeeded_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_Succeeded_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Management.
        /// </summary>
        public static string Nav_DataMgmt_ImportMgmt_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_ImportMgmt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Nav_DataMgmt_Title {
            get {
                return ResourceManager.GetString("Nav_DataMgmt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Nav_Documentation {
            get {
                return ResourceManager.GetString("Nav_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Profile.
        /// </summary>
        public static string Nav_EditBufferProfile_Title {
            get {
                return ResourceManager.GetString("Nav_EditBufferProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Nav_EditCalendar_Title {
            get {
                return ResourceManager.GetString("Nav_EditCalendar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Nav_EditLocations_Title {
            get {
                return ResourceManager.GetString("Nav_EditLocations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Nav_Editors_Title {
            get {
                return ResourceManager.GetString("Nav_Editors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Adjustment Factor.
        /// </summary>
        public static string Nav_EditPAF_Title {
            get {
                return ResourceManager.GetString("Nav_EditPAF_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Nav_EditPart_Title {
            get {
                return ResourceManager.GetString("Nav_EditPart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Nav_Group_Admin {
            get {
                return ResourceManager.GetString("Nav_Group_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Nav_Group_Data {
            get {
                return ResourceManager.GetString("Nav_Group_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string Nav_Group_Editors {
            get {
                return ResourceManager.GetString("Nav_Group_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Nav_Group_Info {
            get {
                return ResourceManager.GetString("Nav_Group_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Group_Settings {
            get {
                return ResourceManager.GetString("Nav_Group_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Nav_Group_Tools {
            get {
                return ResourceManager.GetString("Nav_Group_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home_Title {
            get {
                return ResourceManager.GetString("Nav_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Nav_Info_Title {
            get {
                return ResourceManager.GetString("Nav_Info_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New!.
        /// </summary>
        public static string Nav_Menu_NewBadge {
            get {
                return ResourceManager.GetString("Nav_Menu_NewBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated!.
        /// </summary>
        public static string Nav_Menu_UpdatedBadge {
            get {
                return ResourceManager.GetString("Nav_Menu_UpdatedBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Orders.
        /// </summary>
        public static string Nav_PendingOrders_Title {
            get {
                return ResourceManager.GetString("Nav_PendingOrders_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner Tools.
        /// </summary>
        public static string Nav_Planner_Title {
            get {
                return ResourceManager.GetString("Nav_Planner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ Dashboard.
        /// </summary>
        public static string Nav_PlannersDashboard_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersDashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Nav_PlannersWorkbench_All_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_All_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Nav_PlannersWorkbench_Critical_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_Critical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Nav_PlannersWorkbench_Custom_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_Custom_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Nav_PlannersWorkbench_Green_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_Green_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Green.
        /// </summary>
        public static string Nav_PlannersWorkbench_OToG_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_OToG_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Nav_PlannersWorkbench_Red_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_Red_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (NB).
        /// </summary>
        public static string Nav_PlannersWorkbench_RedNonBuffered_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_RedNonBuffered_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workbench.
        /// </summary>
        public static string Nav_PlannersWorkbench_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Nav_PlannersWorkbench_Yellow_Title {
            get {
                return ResourceManager.GetString("Nav_PlannersWorkbench_Yellow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Summary.
        /// </summary>
        public static string Nav_ReadBufferSummary_Title {
            get {
                return ResourceManager.GetString("Nav_ReadBufferSummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Trend.
        /// </summary>
        public static string Nav_ReadBufferTrend_Title {
            get {
                return ResourceManager.GetString("Nav_ReadBufferTrend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical and High Trend by Planner.
        /// </summary>
        public static string Nav_ReadCritHighPlanner_Title {
            get {
                return ResourceManager.GetString("Nav_ReadCritHighPlanner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OToG Trend by Planner.
        /// </summary>
        public static string Nav_ReadOtogPlanner_Title {
            get {
                return ResourceManager.GetString("Nav_ReadOtogPlanner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Activity.
        /// </summary>
        public static string Nav_ReadPartActivity_Title {
            get {
                return ResourceManager.GetString("Nav_ReadPartActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Distribution.
        /// </summary>
        public static string Nav_ReadPartDistribution_Title {
            get {
                return ResourceManager.GetString("Nav_ReadPartDistribution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out with Demand.
        /// </summary>
        public static string Nav_ReadStockOutDemandTrend_Title {
            get {
                return ResourceManager.GetString("Nav_ReadStockOutDemandTrend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Critical and High.
        /// </summary>
        public static string Nav_ReadSumCritHigh_Title {
            get {
                return ResourceManager.GetString("Nav_ReadSumCritHigh_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of OTOG.
        /// </summary>
        public static string Nav_ReadSumOfOtog_Title {
            get {
                return ResourceManager.GetString("Nav_ReadSumOfOtog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Nav_Reports_Title {
            get {
                return ResourceManager.GetString("Nav_Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Nav_Search_Title {
            get {
                return ResourceManager.GetString("Nav_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings_Title {
            get {
                return ResourceManager.GetString("Nav_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Nav_Status_Title {
            get {
                return ResourceManager.GetString("Nav_Status_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Deployment.
        /// </summary>
        public static string Nav_StockDeployment_Title {
            get {
                return ResourceManager.GetString("Nav_StockDeployment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string Nav_User_Settings_Title {
            get {
                return ResourceManager.GetString("Nav_User_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None selected.
        /// </summary>
        public static string NoneSelected {
            get {
                return ResourceManager.GetString("NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part has no activity.
        /// </summary>
        public static string PartActivity_NoActivity {
            get {
                return ResourceManager.GetString("PartActivity_NoActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part has no demand allocations.
        /// </summary>
        public static string PartActivity_NoDemandAllocations {
            get {
                return ResourceManager.GetString("PartActivity_NoDemandAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part has no supply orders.
        /// </summary>
        public static string PartActivity_NoSupplyOrders {
            get {
                return ResourceManager.GetString("PartActivity_NoSupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Activity.
        /// </summary>
        public static string PartActivity_Tab_AllActivity {
            get {
                return ResourceManager.GetString("PartActivity_Tab_AllActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Allocations.
        /// </summary>
        public static string PartActivity_Tab_DemandAllocations {
            get {
                return ResourceManager.GetString("PartActivity_Tab_DemandAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Orders.
        /// </summary>
        public static string PartActivity_Tab_SupplyOrders {
            get {
                return ResourceManager.GetString("PartActivity_Tab_SupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Actions.
        /// </summary>
        public static string QuickActions {
            get {
                return ResourceManager.GetString("QuickActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select one.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show less.
        /// </summary>
        public static string ShowLess {
            get {
                return ResourceManager.GetString("ShowLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show more.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The displayed times are using the configured site&apos;s global time settings.
        /// </summary>
        public static string TimeZone_Server_Desc1 {
            get {
                return ResourceManager.GetString("TimeZone_Server_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time settings are configured in the Global Settings page.
        /// </summary>
        public static string TimeZone_Server_Desc2 {
            get {
                return ResourceManager.GetString("TimeZone_Server_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User Time Zone (Browser).
        /// </summary>
        public static string TimeZoneType_Browser {
            get {
                return ResourceManager.GetString("TimeZoneType_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured Regional Time Zone (Site).
        /// </summary>
        public static string TimeZoneType_Site {
            get {
                return ResourceManager.GetString("TimeZoneType_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Time Zone (UTC).
        /// </summary>
        public static string TimeZoneType_UTC {
            get {
                return ResourceManager.GetString("TimeZoneType_UTC", resourceCulture);
            }
        }
    }
}
