//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ObjectModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjectModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.ObjectModel", typeof(ObjectModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string Common_Late {
            get {
                return ResourceManager.GetString("Common_Late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string Common_MaterialType {
            get {
                return ResourceManager.GetString("Common_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Common_Notes {
            get {
                return ResourceManager.GetString("Common_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string Common_OrderType {
            get {
                return ResourceManager.GetString("Common_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Type.
        /// </summary>
        public static string Common_PartType {
            get {
                return ResourceManager.GetString("Common_PartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string Common_PlannerCode {
            get {
                return ResourceManager.GetString("Common_PlannerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Common_PriorityCode {
            get {
                return ResourceManager.GetString("Common_PriorityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Profile.
        /// </summary>
        public static string Common_Profile {
            get {
                return ResourceManager.GetString("Common_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Common_Quantity {
            get {
                return ResourceManager.GetString("Common_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Common_Source {
            get {
                return ResourceManager.GetString("Common_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Common_Status {
            get {
                return ResourceManager.GetString("Common_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        public static string Common_UnitOfMeasure {
            get {
                return ResourceManager.GetString("Common_UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Common_Vendor {
            get {
                return ResourceManager.GetString("Common_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        public static string Common_VendorId {
            get {
                return ResourceManager.GetString("Common_VendorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Order_Customer {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Order_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Code.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Order_LinkCode {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Order_LinkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Order_OrderId {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Order_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Order_OrderNumber {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Order_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Order Qty.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Order_RecommendedOrderQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Order_RecommendedOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_OrderKey_OrderNumber {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_OrderKey_OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Daily Use.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Part_AverageDailyUsage {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Part_AverageDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Daily Usage.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Part_EffectiveDailyUsage {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Part_EffectiveDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Lead Time.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Part_FixedLeadTime {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Part_FixedLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasted Daily Usage.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_Part_ForecastedDailyUsage {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_Part_ForecastedDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_Date {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_DueDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Inventory.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_IsInventory {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_IsInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_Line {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_OrderCreationDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_OrderCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Spike Priority.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_OrderSpikePriority {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_OrderSpikePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_OrderType {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promise Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_PromiseDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_PromiseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified Demand Order.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_QualifiedDemandOrder {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_QualifiedDemandOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Status.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_ReminderStatus {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_ReminderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_RequestDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Balance.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_RunningQuantity {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_RunningQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Total Adjustment.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_RunningTotalAdjustment {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_RunningTotalAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_StartDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_ThirdParty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_ThirdPartyId {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_ThirdPartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartActivity_Type {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartActivity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Factor.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_AdjustmentFactor {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_AdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Stock.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_AvailableStock {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_AvailableStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Buffer.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_AvailableStockPercentage {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_AvailableStockPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI Status.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_CurrentInventoryStatus {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_CurrentInventoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Allocations.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_DemandAllocations {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_DemandAllocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_DueDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Zone Buffer Size.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_GreenZoneSize {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_GreenZoneSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Method.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_InventoryMethod {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_InventoryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Qty.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_InventoryQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Qty.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_IssuedQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_IssuedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Status.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_LeadTimeStatus {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_LeadTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTM Total Orders.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_LTMTotalOrders {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_LTMTotalOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSA Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_MaterialSynchronizationDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_MaterialSynchronizationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSA Status.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_MaterialSynchronizationStatus {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_MaterialSynchronizationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hand.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_OnHandQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_OnHandQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Order.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_OrderMaximumQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_OrderMaximumQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Order.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_OrderMinimumQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_OrderMinimumQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Multiple.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_OrderMultipleQty {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_OrderMultipleQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spike.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_OrderSpikeAlert {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_OrderSpikeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Top of Red.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_PercentageOfTopOfRed {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_PercentageOfTopOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Factor Name.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_PlannedAdjustmentFactor {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_PlannedAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Factor Value.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_PlannedAdjustmentFactorValue {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_PlannedAdjustmentFactorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO % of Buffer.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_ProjectedStockOutBufferPercent {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_ProjectedStockOutBufferPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSO Status.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_ProjectedStockOutStatus {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_ProjectedStockOutStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promise Date.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_PromiseDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_PromiseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Qty.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_Quantity {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Zone Buffer Size.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_RedZoneBase {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_RedZoneBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Notes.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_ReminderStatus {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_ReminderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ Alert.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_ReorderPoint {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_ReorderPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPlus Lead Time.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_RPlusLeadTime {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_RPlusLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out Date:.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_StockOutDate {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_StockOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Orders.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_SupplyOrders {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_SupplyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted Inventory.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_TargetedInventory {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_TargetedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToG.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_TopOfGreen {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_TopOfGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToR.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_TopOfRed {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_TopOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToY.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_TopOfYellow {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_TopOfYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Zone Buffer Size.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartDetail_YellowZoneSize {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartDetail_YellowZoneSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartKey_Location {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartKey_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartKey_PartNumber {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartKey_PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PartKey_Revision {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PartKey_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_CreatedByUser {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_CreatedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Cost.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_ExtendedCost {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_ExtendedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Planning.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_InventoryPlanning {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_InventoryPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Item.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_LineItem {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_LineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Buffer.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_PercOfBuffer {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_PercOfBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order Number.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_SalesOrderNumber {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_SalesOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Cost.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_UnitCost {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_UnitCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_Variance {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_Variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance Cost.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_VarianceCost {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_VarianceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance Notes.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_PendingOrder_VarianceNotes {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_PendingOrder_VarianceNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress Order Qty Rules.
        /// </summary>
        public static string DDTech_RPlus_DTO_Engine_RecommendedOrder_SuppressOrderQtyRules {
            get {
                return ResourceManager.GetString("DDTech_RPlus_DTO_Engine_RecommendedOrder_SuppressOrderQtyRules", resourceCulture);
            }
        }
    }
}
