//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PAFEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PAFEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.PAFEditor", typeof(PAFEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Adjustment Factor.
        /// </summary>
        public static string AddAdjustmentFactor {
            get {
                return ResourceManager.GetString("AddAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Factor.
        /// </summary>
        public static string AddFactor {
            get {
                return ResourceManager.GetString("AddFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location:.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAF deleted successfully.
        /// </summary>
        public static string PAFDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PAFDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part added successfully.
        /// </summary>
        public static string PartAddedDuccessfully {
            get {
                return ResourceManager.GetString("PartAddedDuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Adjustment Factors.
        /// </summary>
        public static string PlannedAdjustmentFactors {
            get {
                return ResourceManager.GetString("PlannedAdjustmentFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilter {
            get {
                return ResourceManager.GetString("SelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
    }
}
