//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PartEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.PartEditor", typeof(PartEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Part.
        /// </summary>
        public static string AddNewPart {
            get {
                return ResourceManager.GetString("AddNewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Daily Usage.
        /// </summary>
        public static string AverageDailyUsage {
            get {
                return ResourceManager.GetString("AverageDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Sizing.
        /// </summary>
        public static string BufferSizing {
            get {
                return ResourceManager.GetString("BufferSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer values incompatible with rendering chart..
        /// </summary>
        public static string BufferValuesIncompatibleWithRenderingChart {
            get {
                return ResourceManager.GetString("BufferValuesIncompatibleWithRenderingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PAF is.
        /// </summary>
        public static string CurrentPAFIs {
            get {
                return ResourceManager.GetString("CurrentPAFIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle Day Adjustment Factor.
        /// </summary>
        public static string CycleDayAdjustmentFactor {
            get {
                return ResourceManager.GetString("CycleDayAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {CDAFDaysCoverage} days.
        /// </summary>
        public static string CycleDayAdjustmentFactorDaysCoverage {
            get {
                return ResourceManager.GetString("CycleDayAdjustmentFactorDaysCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Consumption.
        /// </summary>
        public static string DaysConsumption {
            get {
                return ResourceManager.GetString("DaysConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoupled.
        /// </summary>
        public static string DecoupledLeadTime {
            get {
                return ResourceManager.GetString("DecoupledLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Daily Usage.
        /// </summary>
        public static string EffectiveDailyUsage {
            get {
                return ResourceManager.GetString("EffectiveDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Revision.
        /// </summary>
        public static string EnterRevision {
            get {
                return ResourceManager.GetString("EnterRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Avg Inventory.
        /// </summary>
        public static string ExpectedAvgInventory {
            get {
                return ResourceManager.GetString("ExpectedAvgInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Lead Time.
        /// </summary>
        public static string FixedLeadTime {
            get {
                return ResourceManager.GetString("FixedLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasted Daily Usage.
        /// </summary>
        public static string ForecastedDailyUsage {
            get {
                return ResourceManager.GetString("ForecastedDailyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        public static string InventoryManagement {
            get {
                return ResourceManager.GetString("InventoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Order.
        /// </summary>
        public static string MaximumOrder {
            get {
                return ResourceManager.GetString("MaximumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Order.
        /// </summary>
        public static string MinimumOrder {
            get {
                return ResourceManager.GetString("MinimumOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model a Part.
        /// </summary>
        public static string ModelAPart {
            get {
                return ResourceManager.GetString("ModelAPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-buffered and Lead Time Managed parts have no sizing values..
        /// </summary>
        public static string NBAndLTMPartsNoSizingValues {
            get {
                return ResourceManager.GetString("NBAndLTMPartsNoSizingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cycle Override.
        /// </summary>
        public static string OrderCycleOverride {
            get {
                return ResourceManager.GetString("OrderCycleOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Multiple.
        /// </summary>
        public static string OrderMultiple {
            get {
                return ResourceManager.GetString("OrderMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Policy.
        /// </summary>
        public static string OrderPolicy {
            get {
                return ResourceManager.GetString("OrderPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Sourced Cost.
        /// </summary>
        public static string OutSourcedCost {
            get {
                return ResourceManager.GetString("OutSourcedCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part added successfully.
        /// </summary>
        public static string PartAddedSuccessfully {
            get {
                return ResourceManager.GetString("PartAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part deleted successfully.
        /// </summary>
        public static string PartDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PartDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part saved successfully.
        /// </summary>
        public static string PartSavedSuccessfully {
            get {
                return ResourceManager.GetString("PartSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts Edit.
        /// </summary>
        public static string PartsEdit {
            get {
                return ResourceManager.GetString("PartsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Type.
        /// </summary>
        public static string PartType {
            get {
                return ResourceManager.GetString("PartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Adjustment Factor.
        /// </summary>
        public static string PlannedAdjustmentFactor {
            get {
                return ResourceManager.GetString("PlannedAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner Code.
        /// </summary>
        public static string PlannerCode {
            get {
                return ResourceManager.GetString("PlannerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Cost.
        /// </summary>
        public static string RawMaterialCost {
            get {
                return ResourceManager.GetString("RawMaterialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev.
        /// </summary>
        public static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ Lead Time.
        /// </summary>
        public static string RPlusLeadTime {
            get {
                return ResourceManager.GetString("RPlusLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Part....
        /// </summary>
        public static string SearchPart {
            get {
                return ResourceManager.GetString("SearchPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter.
        /// </summary>
        public static string SelectFilter {
            get {
                return ResourceManager.GetString("SelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Green.
        /// </summary>
        public static string TopOfGreen {
            get {
                return ResourceManager.GetString("TopOfGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Green cannot be less than Top of Yellow.
        /// </summary>
        public static string TopOfGreenCannotBeLessThanTopOfYellow {
            get {
                return ResourceManager.GetString("TopOfGreenCannotBeLessThanTopOfYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Red.
        /// </summary>
        public static string TopOfRed {
            get {
                return ResourceManager.GetString("TopOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Yellow.
        /// </summary>
        public static string TopOfYellow {
            get {
                return ResourceManager.GetString("TopOfYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Yellow cannot be less than Top of Red.
        /// </summary>
        public static string TopOfYellowCannotBeLessThanTopOfRed {
            get {
                return ResourceManager.GetString("TopOfYellowCannotBeLessThanTopOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Zone.
        /// </summary>
        public static string TopOfZone {
            get {
                return ResourceManager.GetString("TopOfZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 1.
        /// </summary>
        public static string UDF1 {
            get {
                return ResourceManager.GetString("UDF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 2.
        /// </summary>
        public static string UDF2 {
            get {
                return ResourceManager.GetString("UDF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 3.
        /// </summary>
        public static string UDF3 {
            get {
                return ResourceManager.GetString("UDF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 4.
        /// </summary>
        public static string UDF4 {
            get {
                return ResourceManager.GetString("UDF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 5.
        /// </summary>
        public static string UDF5 {
            get {
                return ResourceManager.GetString("UDF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 6.
        /// </summary>
        public static string UDF6 {
            get {
                return ResourceManager.GetString("UDF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 7.
        /// </summary>
        public static string UDF7 {
            get {
                return ResourceManager.GetString("UDF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined 8.
        /// </summary>
        public static string UDF8 {
            get {
                return ResourceManager.GetString("UDF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Measure.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Defined Fields.
        /// </summary>
        public static string UserDefinedFields {
            get {
                return ResourceManager.GetString("UserDefinedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Identifier.
        /// </summary>
        public static string VendorIdentifier {
            get {
                return ResourceManager.GetString("VendorIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Size.
        /// </summary>
        public static string ZoneSize {
            get {
                return ResourceManager.GetString("ZoneSize", resourceCulture);
            }
        }
    }
}
