//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Reports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Reports", typeof(Reports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ API Token (i.e. add.
        /// </summary>
        public static string AuthModeDesc_RPlusApiToken1 {
            get {
                return ResourceManager.GetString("AuthModeDesc_RPlusApiToken1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to the endpoint address).
        /// </summary>
        public static string AuthModeDesc_RPlusApiToken2 {
            get {
                return ResourceManager.GetString("AuthModeDesc_RPlusApiToken2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Trend.
        /// </summary>
        public static string BufferTrend {
            get {
                return ResourceManager.GetString("BufferTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical and High.
        /// </summary>
        public static string CriticalAndHigh {
            get {
                return ResourceManager.GetString("CriticalAndHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical and High Trend by Planner.
        /// </summary>
        public static string CriticalAndHighTrendByPlanner {
            get {
                return ResourceManager.GetString("CriticalAndHighTrendByPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Reports.
        /// </summary>
        public static string CustomReports {
            get {
                return ResourceManager.GetString("CustomReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range:.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Planning:.
        /// </summary>
        public static string InventoryPlanning {
            get {
                return ResourceManager.GetString("InventoryPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Type:.
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft&apos;s Power BI.
        /// </summary>
        public static string MicrosoftsPowerBI {
            get {
                return ResourceManager.GetString("MicrosoftsPowerBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hand.
        /// </summary>
        public static string OnHand {
            get {
                return ResourceManager.GetString("OnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OToG.
        /// </summary>
        public static string OTOG {
            get {
                return ResourceManager.GetString("OTOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OToG Trend by Planner.
        /// </summary>
        public static string OTOGTrendByPlanner {
            get {
                return ResourceManager.GetString("OTOGTrendByPlanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Top of Green.
        /// </summary>
        public static string OverTopOfGreen {
            get {
                return ResourceManager.GetString("OverTopOfGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Distribution.
        /// </summary>
        public static string PartDistribution {
            get {
                return ResourceManager.GetString("PartDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Type:.
        /// </summary>
        public static string PartType {
            get {
                return ResourceManager.GetString("PartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planner Code:.
        /// </summary>
        public static string PlannerCode {
            get {
                return ResourceManager.GetString("PlannerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Defined Reports.
        /// </summary>
        public static string PreDefinedReports {
            get {
                return ResourceManager.GetString("PreDefinedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended for use with.
        /// </summary>
        public static string RecommendedForUseWith {
            get {
                return ResourceManager.GetString("RecommendedForUseWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R+ OData API.
        /// </summary>
        public static string RPlusODataApi {
            get {
                return ResourceManager.GetString("RPlusODataApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The R+ OData endpoint supports the following authentication methods.
        /// </summary>
        public static string RPlusODataEndpointSupportsTheFollowingAuth {
            get {
                return ResourceManager.GetString("RPlusODataEndpointSupportsTheFollowingAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out with Demand.
        /// </summary>
        public static string StockOutWithDemand {
            get {
                return ResourceManager.GetString("StockOutWithDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Critical and High.
        /// </summary>
        public static string SumOfCriticalAndHigh {
            get {
                return ResourceManager.GetString("SumOfCriticalAndHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of OTOG.
        /// </summary>
        public static string SumOfOTOG {
            get {
                return ResourceManager.GetString("SumOfOTOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Inventory.
        /// </summary>
        public static string TargetInventory {
            get {
                return ResourceManager.GetString("TargetInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
