//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Setup", typeof(Setup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Administrator has been registered. Instructions to set a password have been sent to the email address specified..
        /// </summary>
        public static string Admin_Confirm {
            get {
                return ResourceManager.GetString("Admin_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first create your first Administrator. This user will be able to manage any other users..
        /// </summary>
        public static string Admin_Message {
            get {
                return ResourceManager.GetString("Admin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Admin_Title {
            get {
                return ResourceManager.GetString("Admin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Homepage.
        /// </summary>
        public static string Done_Action_Home {
            get {
                return ResourceManager.GetString("Done_Action_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Additional Users.
        /// </summary>
        public static string Done_Action_Users {
            get {
                return ResourceManager.GetString("Done_Action_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup of your RPlus instance is complete!.
        /// </summary>
        public static string Done_Message {
            get {
                return ResourceManager.GetString("Done_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Complete.
        /// </summary>
        public static string Done_Title {
            get {
                return ResourceManager.GetString("Done_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your instance of RPlus is almost ready for you to use. We only need to collect a few bits of information before you continue..
        /// </summary>
        public static string Index_Message {
            get {
                return ResourceManager.GetString("Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-Time Setup.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance of RPlus requires a valid license. Please upload one to continue..
        /// </summary>
        public static string License_Message {
            get {
                return ResourceManager.GetString("License_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License_Title {
            get {
                return ResourceManager.GetString("License_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
    }
}
