//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Of Material.
        /// </summary>
        public static string BillOfMaterial {
            get {
                return ResourceManager.GetString("BillOfMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer Profile.
        /// </summary>
        public static string BufferProfile {
            get {
                return ResourceManager.GetString("BufferProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Child Allocations On Pending Order Creation.
        /// </summary>
        public static string CreateChildAllocationsOnPendingOrderCreation {
            get {
                return ResourceManager.GetString("CreateChildAllocationsOnPendingOrderCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Child Allocations On Supply Order Import.
        /// </summary>
        public static string CreateChildAllocationsOnSupplyOrderImport {
            get {
                return ResourceManager.GetString("CreateChildAllocationsOnSupplyOrderImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Local Time.
        /// </summary>
        public static string CurrentLocalTime {
            get {
                return ResourceManager.GetString("CurrentLocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time Zone.
        /// </summary>
        public static string CurrentTimeZone {
            get {
                return ResourceManager.GetString("CurrentTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Set Statistics.
        /// </summary>
        public static string DataSetStatistics {
            get {
                return ResourceManager.GetString("DataSetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Inventory Alert Level.
        /// </summary>
        public static string DefaultInventoryAlertLevel {
            get {
                return ResourceManager.GetString("DefaultInventoryAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Order Spike Alert Level.
        /// </summary>
        public static string DefaultOrderSpikeAlertLevel {
            get {
                return ResourceManager.GetString("DefaultOrderSpikeAlertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Order Spike Horizon Level.
        /// </summary>
        public static string DefaultOrderSpikeHorizonLevel {
            get {
                return ResourceManager.GetString("DefaultOrderSpikeHorizonLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Order.
        /// </summary>
        public static string DemandOrder {
            get {
                return ResourceManager.GetString("DemandOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Order Window For Sales Orders.
        /// </summary>
        public static string DemandOrderWindowForSalesOrders {
            get {
                return ResourceManager.GetString("DemandOrderWindowForSalesOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Order Window For Work Orders.
        /// </summary>
        public static string DemandOrderWindowForWorkOrders {
            get {
                return ResourceManager.GetString("DemandOrderWindowForWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecasted Demand.
        /// </summary>
        public static string ForecastedDemand {
            get {
                return ResourceManager.GetString("ForecastedDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Capture Log.
        /// </summary>
        public static string HistoryCaptureLog_Btn {
            get {
                return ResourceManager.GetString("HistoryCaptureLog_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Time Zone Information.
        /// </summary>
        public static string LocalTimeZoneInfo {
            get {
                return ResourceManager.GetString("LocalTimeZoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Augment.
        /// </summary>
        public static string PartAugment {
            get {
                return ResourceManager.GetString("PartAugment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Buffer Sizing.
        /// </summary>
        public static string PartBufferSizing {
            get {
                return ResourceManager.GetString("PartBufferSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Inventory.
        /// </summary>
        public static string PartInventory {
            get {
                return ResourceManager.GetString("PartInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Metrics.
        /// </summary>
        public static string PerformanceMetrics {
            get {
                return ResourceManager.GetString("PerformanceMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Adjustment Factor.
        /// </summary>
        public static string PlannedAdjustmentFactor {
            get {
                return ResourceManager.GetString("PlannedAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Stock Out Lead Time Horizon.
        /// </summary>
        public static string ProjectedStockOutLeadTimeHorizon {
            get {
                return ResourceManager.GetString("ProjectedStockOutLeadTimeHorizon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Buffer Values To One.
        /// </summary>
        public static string RoundBufferValuesToOne {
            get {
                return ResourceManager.GetString("RoundBufferValuesToOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Status.
        /// </summary>
        public static string SiteStatus {
            get {
                return ResourceManager.GetString("SiteStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply Order.
        /// </summary>
        public static string SupplyOrder {
            get {
                return ResourceManager.GetString("SupplyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 1.
        /// </summary>
        public static string UserDefined1 {
            get {
                return ResourceManager.GetString("UserDefined1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 2.
        /// </summary>
        public static string UserDefined2 {
            get {
                return ResourceManager.GetString("UserDefined2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 3.
        /// </summary>
        public static string UserDefined3 {
            get {
                return ResourceManager.GetString("UserDefined3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 4.
        /// </summary>
        public static string UserDefined4 {
            get {
                return ResourceManager.GetString("UserDefined4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 5.
        /// </summary>
        public static string UserDefined5 {
            get {
                return ResourceManager.GetString("UserDefined5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 6.
        /// </summary>
        public static string UserDefined6 {
            get {
                return ResourceManager.GetString("UserDefined6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 7.
        /// </summary>
        public static string UserDefined7 {
            get {
                return ResourceManager.GetString("UserDefined7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined 8.
        /// </summary>
        public static string UserDefined8 {
            get {
                return ResourceManager.GetString("UserDefined8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View additional status details.
        /// </summary>
        public static string ViewAdditionalStatusDetails {
            get {
                return ResourceManager.GetString("ViewAdditionalStatusDetails", resourceCulture);
            }
        }
    }
}
