//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockDeployment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockDeployment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.StockDeployment", typeof(StockDeployment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Deployment.
        /// </summary>
        public static string AfterDeployment {
            get {
                return ResourceManager.GetString("AfterDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string AfterDeploymentAvailabeStock {
            get {
                return ResourceManager.GetString("AfterDeploymentAvailabeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After % of Green.
        /// </summary>
        public static string AfterDeploymentPercentOfTopOfGreen {
            get {
                return ResourceManager.GetString("AfterDeploymentPercentOfTopOfGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available To-Deploy.
        /// </summary>
        public static string AvailableToDeploy {
            get {
                return ResourceManager.GetString("AvailableToDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before Deployment.
        /// </summary>
        public static string BeforeDeployment {
            get {
                return ResourceManager.GetString("BeforeDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string BeforeDeploymentAvailableStock {
            get {
                return ResourceManager.GetString("BeforeDeploymentAvailableStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before % of Green.
        /// </summary>
        public static string BeforeDeploymentPercentOfTopOfGreen {
            get {
                return ResourceManager.GetString("BeforeDeploymentPercentOfTopOfGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Work Orders.
        /// </summary>
        public static string CurrentWorkOrders {
            get {
                return ResourceManager.GetString("CurrentWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Export Type.
        /// </summary>
        public static string DefaultExportType {
            get {
                return ResourceManager.GetString("DefaultExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Window (days).
        /// </summary>
        public static string DemandWindowDays {
            get {
                return ResourceManager.GetString("DemandWindowDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed to.
        /// </summary>
        public static string DeployedTo {
            get {
                return ResourceManager.GetString("DeployedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Mode.
        /// </summary>
        public static string DeploymentMode {
            get {
                return ResourceManager.GetString("DeploymentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct.
        /// </summary>
        public static string DeploymentMode_Direct {
            get {
                return ResourceManager.GetString("DeploymentMode_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub.
        /// </summary>
        public static string DeploymentMode_Hub {
            get {
                return ResourceManager.GetString("DeploymentMode_Hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Requirement.
        /// </summary>
        public static string DeploymentRequirement {
            get {
                return ResourceManager.GetString("DeploymentRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Details.
        /// </summary>
        public static string DestinationDetails {
            get {
                return ResourceManager.GetString("DestinationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations.
        /// </summary>
        public static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Deployment Module is currently disabled..
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Type.
        /// </summary>
        public static string ExportType {
            get {
                return ResourceManager.GetString("ExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string ExportType_CSV {
            get {
                return ResourceManager.GetString("ExportType_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLXP.
        /// </summary>
        public static string ExportType_DLXP {
            get {
                return ResourceManager.GetString("ExportType_DLXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM: Destination Details.
        /// </summary>
        public static string GridDestinationDetails {
            get {
                return ResourceManager.GetString("GridDestinationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM: Destination Summary.
        /// </summary>
        public static string GridDestinationSummary {
            get {
                return ResourceManager.GetString("GridDestinationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM: Sources.
        /// </summary>
        public static string GridSources {
            get {
                return ResourceManager.GetString("GridSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holdback.
        /// </summary>
        public static string Holdback {
            get {
                return ResourceManager.GetString("Holdback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Issued Quantity in Holdback.
        /// </summary>
        public static string IncludeIssued {
            get {
                return ResourceManager.GetString("IncludeIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Inventory.
        /// </summary>
        public static string IssuedInventory {
            get {
                return ResourceManager.GetString("IssuedInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar look ahead days.
        /// </summary>
        public static string LookAheadDays {
            get {
                return ResourceManager.GetString("LookAheadDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Holdback.
        /// </summary>
        public static string MinimumHoldbackPercentOfRed {
            get {
                return ResourceManager.GetString("MinimumHoldbackPercentOfRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source selected.
        /// </summary>
        public static string NoSourceSelected {
            get {
                return ResourceManager.GetString("NoSourceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Multiple Adjustment.
        /// </summary>
        public static string OrderMultipleAdjustment {
            get {
                return ResourceManager.GetString("OrderMultipleAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualified Demand.
        /// </summary>
        public static string QualifiedDemand {
            get {
                return ResourceManager.GetString("QualifiedDemand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Override.
        /// </summary>
        public static string ResetOverride {
            get {
                return ResourceManager.GetString("ResetOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Places to Use for Calculations.
        /// </summary>
        public static string Settings_DecimalPlacesForCalculations {
            get {
                return ResourceManager.GetString("Settings_DecimalPlacesForCalculations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Deployment is disabled.
        /// </summary>
        public static string Settings_Disabled {
            get {
                return ResourceManager.GetString("Settings_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export File Name.
        /// </summary>
        public static string Settings_ExportFileNameBase {
            get {
                return ResourceManager.GetString("Settings_ExportFileNameBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Hub Deployment Only).
        /// </summary>
        public static string Settings_MinimumHoldbackPercentOfRed_Desc {
            get {
                return ResourceManager.GetString("Settings_MinimumHoldbackPercentOfRed_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source override.
        /// </summary>
        public static string Settings_SourceOverride {
            get {
                return ResourceManager.GetString("Settings_SourceOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Field for Source Location.
        /// </summary>
        public static string Settings_SourceUnitFieldNum {
            get {
                return ResourceManager.GetString("Settings_SourceUnitFieldNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using shared settings.
        /// </summary>
        public static string Settings_UsingShared {
            get {
                return ResourceManager.GetString("Settings_UsingShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Settings.
        /// </summary>
        public static string SharedSettings {
            get {
                return ResourceManager.GetString("SharedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortfall.
        /// </summary>
        public static string Shortfall {
            get {
                return ResourceManager.GetString("Shortfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Details.
        /// </summary>
        public static string SourceDetails {
            get {
                return ResourceManager.GetString("SourceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a source..
        /// </summary>
        public static string SourceDetails_SelectOne {
            get {
                return ResourceManager.GetString("SourceDetails_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Location.
        /// </summary>
        public static string SourceLocation {
            get {
                return ResourceManager.GetString("SourceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string SourceProperties {
            get {
                return ResourceManager.GetString("SourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Settings.
        /// </summary>
        public static string SourceSettings {
            get {
                return ResourceManager.GetString("SourceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Deployment.
        /// </summary>
        public static string StockDeploymentStr {
            get {
                return ResourceManager.GetString("StockDeploymentStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Deployed.
        /// </summary>
        public static string TotalDeployed {
            get {
                return ResourceManager.GetString("TotalDeployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployed to Buffers.
        /// </summary>
        public static string TotalDeployedToBuffers {
            get {
                return ResourceManager.GetString("TotalDeployedToBuffers", resourceCulture);
            }
        }
    }
}
