//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTech.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDTech.Localization.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate LinkCode Encountered.
        /// </summary>
        public static string DuplicateLinkCode {
            get {
                return ResourceManager.GetString("DuplicateLinkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Record.
        /// </summary>
        public static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must fall on same day of week of other records.
        /// </summary>
        public static string ForecastInvalidDayOfWeek {
            get {
                return ResourceManager.GetString("ForecastInvalidDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be greater than or equal to &apos;{PropertyValue}&apos;.
        /// </summary>
        public static string GreaterThanOrEqualToFormat {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid Buffer Profile.
        /// </summary>
        public static string InvalidBufferProfile {
            get {
                return ResourceManager.GetString("InvalidBufferProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid InventoryMethod.
        /// </summary>
        public static string InvalidInventoryMethod {
            get {
                return ResourceManager.GetString("InvalidInventoryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a valid Planned Adjustment Factor (PAF).
        /// </summary>
        public static string InvalidPaf {
            get {
                return ResourceManager.GetString("InvalidPaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be less than or equal to &apos;{PropertyValue}&apos;.
        /// </summary>
        public static string LessThanOrEqualToFormat {
            get {
                return ResourceManager.GetString("LessThanOrEqualToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be less than or equal to &apos;{BadValue}&apos; and has been reset to &apos;{DefaultValue}&apos;.
        /// </summary>
        public static string LessThanOrEqualToWithDefaultValueFormat {
            get {
                return ResourceManager.GetString("LessThanOrEqualToWithDefaultValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be evenly divisible by &apos;{BadValue}&apos; and has been reset to &apos;{DefaultValue}&apos;.
        /// </summary>
        public static string MustBeEvenlyDivisbleWithDefaultValueFormat {
            get {
                return ResourceManager.GetString("MustBeEvenlyDivisbleWithDefaultValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; should not be null or contain whitespace..
        /// </summary>
        public static string notnullorwhitespace_error {
            get {
                return ResourceManager.GetString("notnullorwhitespace_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; out of range and has been reset to &apos;{DefaultValue}&apos;.
        /// </summary>
        public static string OutOfRangeWithDefaultValueFormat {
            get {
                return ResourceManager.GetString("OutOfRangeWithDefaultValueFormat", resourceCulture);
            }
        }
    }
}
